dandelion-community/dandelion

- .github/workflows/deploy-to-eb.yaml
- views/index.jade
I'd like to merge this into `latest`! Since this PR is from the `chris` branch, you can see it live at [http://chris.dandelion.supplies](http://chris.dandelion.supplies). Please check it out and approve if it looks good to you!
> Adding the latest feature!

- package.json
This resolves #9 but probably not in the "right" way
> add `yarn install` to `npm run dev:web`

- src/server/aid_requests/index.ts
- src/server/graphql/schema.ts
- yarn.lock
https://user-images.githubusercontent.com/4309735/146652901-0412e9a9-4c7e-4a7d-be3a-0d542c18c007.mov
> GraphQL mutation for creating an aid request

- .eslintrc.js
- .github/workflows/check-eslint.yaml
- .github/workflows/deploy-to-aws.yaml
- src/client/aid-app/navigation/useCreateCrumbtrailsToLandingScreenIfNeeded.ts
- src/client/aid-app/screens/CreateAccountScreen.tsx
- src/client/aid-app/screens/LoginScreen.tsx
- src/server/models/AidRequest.ts
- src/server/models/User.ts
- src/server/models/user_model.ts
I tried to fix the was deployment as well but there's something wrong with it, I still don't know what. maybe something about the node version.
> Fix eslint action

- src/client/aid-app/aid_requests/AidRequestCard.tsx
woooo i changed the ui! I'm a computer coder
> bold "who is it for"

- .github/workflows/android-build.yaml
- .github/workflows/ios-build.yaml
- package.json
- src/client/aid-app/graphql/GraphQLClientURI.ts
- src/client/aid-app/graphql/client.ts
- src/client/aid-app/graphql/createClient.ts
- src/client/aid-app/menu/debug/DebugInfo.tsx
- src/client/aid-app/menu/debug/DebugInfoCard.tsx
- src/client/aid-app/menu/debug/DebugInfoSection.tsx
- src/client/aid-app/menu/debug/DenseText.tsx
- src/client/aid-app/menu/debug/ExpoConstantsSummary.tsx
- src/client/aid-app/menu/debug/GraphQLErrorSummary.tsx
- src/client/aid-app/menu/debug/GraphQLHostDiagnostics.tsx
- src/client/aid-app/menu/debug/GraphQLResponseSummary.tsx
- src/client/aid-app/menu/debug/NetworkDebugInfo.tsx
- src/client/aid-app/menu/debug/NetworkDiagnostics.tsx
- src/client/aid-app/menu/debug/SmallText.tsx
- src/client/aid-app/navigation/LinkingConfiguration.ts
- src/client/aid-app/screens/ThreeLinesMenuRootScreen.tsx
- src/client/general-purpose/components/light-or-dark-themed/PressableText.tsx
- src/client/general-purpose/utils/usePromise.ts
- src/client/general-purpose/viewer/YourAccountMenuCard.tsx
- src/server/root/express_app.ts
- yarn.lock
Debug views:
Not logged in (viewing from port 19006, with server on port 3000):
https://user-images.githubusercontent.com/4309735/147422210-df28c6d8-6330-4478-8ef0-c9431233a8cc.mov
Logged in (client and server both on port 3000):
https://user-images.githubusercontent.com/4309735/147422220-9d2d3d4a-0775-4b9b-8d31-8fcddacc97d8.mov
> Network Debugging

- src/server/objects/user/UserModel.ts
- src/server/root/express_app.ts
http://latest.dandelion.supplies
> Fix deployment

- __generated__/globalTypes.ts
- src/client/aid-app/aid_requests/AidRequestCompleteToggle.tsx
- src/client/aid-app/aid_requests/AidRequestWorkingOnItSummary.tsx
- src/client/aid-app/aid_requests/ListOfAidRequests.tsx
- src/client/aid-app/aid_requests/__generated__/ListOfAidRequestsQuery.ts
- src/client/aid-app/graphql/createClient.ts
- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerFilterButton.tsx
- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerFilters.tsx
- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerScreen.tsx
- src/client/aid-app/navigation/screens/main/request_explorer/filters/RequestExplorerFiltersContext.ts
- src/client/general-purpose/utils/DebouncedLoadingIndicator.tsx
- src/client/general-purpose/viewer/ViewerContext.ts
- src/client/general-purpose/viewer/__generated__/ViewerQuery.ts
- src/client/general-purpose/viewer/useLoadViewer.ts
https://user-images.githubusercontent.com/4309735/148623781-e34b988b-03f9-4b03-9bcf-467468877afd.mov
> Toggles for Me and Complete

- src/server/objects/aid_request/AidRequestGraphQLImpl.ts
- src/server/objects/aid_request/AidRequestGraphQLTypes.ts
- src/server/objects/aid_request/AidRequestModel.ts
- src/server/objects/aid_request/AidRequestModelTypes.ts
- src/server/objects/aid_request/object_fields/history.ts
- src/server/objects/aid_request/object_fields/whoIsWorkingOnItUsers.ts
- src/server/objects/user/UserModel.ts
- src/server/objects/user/UserModelTypes.ts
- src/server/objects/user/object_fields/aidRequestsIAmWorkingOn.ts
> Request history graphql

- package.json
- src/server/objects/aid_request/AidRequestGraphQLImpl.ts
- src/server/objects/aid_request/object_fields/latestEvent.ts
- src/server/tsconfig.json
- yarn.lock
> basic support for latest activity

- src/server/objects/aid_request/object_fields/latestEvent.ts
> show when a request was recorded

- src/server/objects/aid_request/AidRequestModel.ts
> fix 'me' query

- src/server/objects/aid_request/object_fields/latestEvent.ts
- src/server/objects/user/UserGraphQLTypes.ts
- src/server/objects/user/UserModel.ts
- src/server/objects/user/UserModelTypes.ts
for the "Foo recorded it" to use displayName rather than email, probs best to start attaching an actual use object to the aidRequest rather than just the email string
> use displayName for events

- __generated__/globalTypes.ts
- src/client/aid-app/aid_requests/AidRequestCard.tsx
- src/client/aid-app/aid_requests/AidRequestCardFragments.ts
- src/client/aid-app/aid_requests/AidRequestWorkingOnItSummary.tsx
- src/client/aid-app/aid_requests/CreateRequestForm.tsx
- src/client/aid-app/aid_requests/__generated__/AidRequestCardFragment.ts
- src/client/aid-app/aid_requests/__generated__/ListOfAidRequestsQuery.ts
- src/client/aid-app/aid_requests/__generated__/updateIsAidRequestCompleteMutation.ts
- src/client/general-purpose/viewer/ViewerContext.ts
- src/client/general-purpose/viewer/__generated__/LogoutActionMutation.ts
- src/client/general-purpose/viewer/__generated__/ViewerQuery.ts
- src/client/general-purpose/viewer/useLoadViewer.ts
- src/server/objects/aid_request/AidRequestGraphQLImpl.ts
- src/server/objects/aid_request/AidRequestModel.ts
- src/server/objects/aid_request/AidRequestModelTypes.ts
- src/server/objects/aid_request/mutations/createAidRequest.ts
- src/server/objects/aid_request/object_fields/whoRecordedIt.ts
https://user-images.githubusercontent.com/4309735/148862175-fe9f759d-3e64-49e8-85e6-1d4171b3c34e.mov
> Show display names everywhere

- src/client/aid-app/aid_requests/AidRequestCard.tsx
- src/client/aid-app/aid_requests/AidRequestCardFragments.ts
- src/client/aid-app/aid_requests/__generated__/AidRequestCardFragment.ts
- src/client/aid-app/aid_requests/__generated__/ListOfAidRequestsQuery.ts
- src/client/aid-app/aid_requests/__generated__/updateIsAidRequestCompleteMutation.ts
- src/server/objects/aid_request/helpers/getWhoRecordedRequest.ts
- src/server/objects/aid_request/object_fields/latestEvent.ts
- src/server/objects/aid_request/object_fields/whoRecordedIt.ts
> show latest activity in request card

- __generated__/globalTypes.ts
- src/client/aid-app/aid_requests/AidRequestCard.tsx
- src/client/aid-app/aid_requests/AidRequestCardFragments.ts
- src/client/aid-app/aid_requests/AidRequestEditDrawer.tsx
- src/client/aid-app/aid_requests/__generated__/AidRequestCardFragment.ts
- src/client/aid-app/aid_requests/__generated__/ListOfAidRequestsQuery.ts
- src/client/aid-app/aid_requests/__generated__/updateIsAidRequestCompleteMutation.ts
- src/server/objects/aid_request/AidRequestGraphQLImpl.ts
- src/server/objects/aid_request/AidRequestGraphQLTypes.ts
- src/server/objects/aid_request/AidRequestModel.ts
- src/server/objects/aid_request/AidRequestModelTypes.ts
- src/server/objects/aid_request/mutations/createAidRequest.ts
- src/server/objects/aid_request/mutations/updateIsAidRequestComplete.ts
- src/server/objects/aid_request/mutations/updateWhetherIAmWorkingOnThisAidRequest.ts
- src/server/objects/aid_request/object_fields/actionsAvailable.ts
- src/server/objects/aid_request/object_fields/latestEvent.ts
- src/server/objects/user/mutations/register.ts
This loads and shows the edit options. The next step will be to implement mutating the aid request when one of the edit options is selected.
https://user-images.githubusercontent.com/4309735/149016812-3bcf3017-6ba5-408f-8a7b-c3b1a11a54df.mov
> Show edit options in drawer

- src/client/aid-app/aid_requests/AidRequestCard.tsx
- src/client/aid-app/aid_requests/ListOfAidRequests.tsx
- src/client/aid-app/navigation/LinkingConfiguration.ts
- src/client/aid-app/navigation/NavigationTypes.ts
- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerScreen.tsx
- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerTabStackContainer.tsx
- src/client/aid-app/navigation/screens/main/request_explorer/RequestHistoryScreen.tsx
needs back button, also actual history
Co-Authored-By: Chris Barker <chris@cbarker.net>
> stub for request history stack screen

- src/client/aid-app/aid_requests/CreateRequestForm.tsx
https://user-images.githubusercontent.com/3479724/149225168-6dbe69e6-812b-4f21-b7e4-15fb84f2f825.mov
> sticky requester

- src/server/collections/aid_request/object_fields/latestEvent.ts
> created this -> recorded this

- src/client/aid-app/navigation/screens/main/request_explorer/RequestExplorerFilters.tsx
https://user-images.githubusercontent.com/3479724/149830470-e4c31d4f-1cd2-492b-b208-5cb831a5151d.mov
> show filter description text

- .gitignore
- src/client/aid-app/aid_requests/__generated__/AidRequestEditDrawerFragment.ts
- src/client/aid-app/aid_requests/__generated__/AidRequestWorkingOnItSummaryFragment.ts
- src/client/aid-app/aid_requests/__generated__/CreateAidRequestMutation.ts
- src/client/aid-app/aid_requests/__generated__/editAidRequestMutation.ts
- src/client/aid-app/aid_requests/__generated__/updateWhetherIAmWorkingOnThisAidRequestMutation.ts
- src/client/aid-app/menu/attribution/AttributionCard.tsx
- src/client/aid-app/menu/attribution/__generated__/AttributionCardQuery.ts
- src/client/aid-app/menu/debug/__generated__/SpotCheckMeQuery.ts
- src/client/aid-app/navigation/screens/create_account/__generated__/Register.ts
- src/client/aid-app/navigation/screens/login/__generated__/Login.ts
- src/client/aid-app/navigation/screens/main/three_lines_menu/ThreeLinesMenuScreen.tsx
- src/server/collections/user/root_fields/attribution/attribution-config.json
- src/server/collections/user/root_fields/attribution/attributions.ts
- src/server/graphql/GraphQLSchema.ts
> Show attributions

- .github/workflows/deploy-to-aws.yaml
- build_server.sh
- package.json
- src/.babelrc.json
- src/client/graphql/createClient.ts
- src/client/request_explorer/ListOfAidRequests.tsx
- src/client/request_explorer/ListOfAidRequestsQuery.ts
- yarn.lock
Fixes an issue where the same request was sometimes added to the request list multiple times
> Fix duplicate list entries

- src/client/menu/FeedbackCard.tsx
- src/client/menu/SupportAppCard.tsx
- src/client/menu/ThreeLinesMenuScreen.tsx
pls feel free to suggest alternate wordingggg
https://user-images.githubusercontent.com/3479724/150210757-b60e0b27-2d88-4679-9215-6e6e83b6a67d.mov
> feedback & support cards

- src/client/create_request/__generated__/CreateAidRequestMutation.ts
- src/client/request_explorer/AidRequestCard.tsx
- src/client/request_explorer/AidRequestCardFragments.ts
- src/client/request_explorer/__generated__/AidRequestCardFragment.ts
- src/client/request_explorer/__generated__/AidRequestEditDrawerFragment.ts
- src/client/request_explorer/__generated__/ListOfAidRequestsQuery.ts
- src/client/request_explorer/__generated__/editAidRequestMutation.ts
https://user-images.githubusercontent.com/3479724/150253015-2f4fb115-555f-4832-989f-624ac3f2f736.mov
> integrate communication tooling

- package.json
- src/client/components/Colors.ts
- src/client/components/EndOfListSpacer.tsx
- src/client/create_request/AidRequestCreateDrawer.tsx
- src/client/menu/ThreeLinesMenuScreen.tsx
- src/client/navigation/bottom-navigator/BottomNavigation.tsx
- src/client/navigation/bottom-navigator/BottomNavigationRouteScreen.tsx
- src/client/navigation/bottom-navigator/Icon.tsx
- src/client/navigation/bottom-navigator/MaterialBottomTabView.tsx
- src/client/navigation/bottom-navigator/createMaterialBottomTabNavigator.tsx
- src/client/navigation/bottom-navigator/types.ts
- src/client/navigation/bottom-navigator/useIsKeyboardShown.ts
- src/client/navigation/screens/main/MainScreen.tsx
- src/client/request_explorer/ListOfAidRequests.tsx
- src/client/toast/ToastProvider.tsx
This isn't supported by react-native-paper so I "forked" their code and created a custom implementation for the bottom bar cutout.
https://user-images.githubusercontent.com/4309735/150648469-98fbd3b8-900c-4154-9215-244c182f50a7.mov
https://user-images.githubusercontent.com/4309735/150648472-cd54bc17-10ae-432a-a5c5-6af128d89b3e.mov
Also works on iOS and Android.
> Create cutout fab

- src/client/create_request/AidRequestCreateDrawer.tsx
- src/client/menu/SupportAppCard.tsx
- src/client/request_explorer/RequestExplorerHeader.tsx
- src/server/collections/aid_request/object_fields/latestEvent.ts
Tested in web on multiple devices.
Android:
https://user-images.githubusercontent.com/4309735/150698662-defecc48-0aae-4cf0-b512-729173af7994.mov
iOS:
https://user-images.githubusercontent.com/4309735/150698669-1f28ca47-6970-463d-8361-23cc7a8a7f00.mov
Mac:
https://user-images.githubusercontent.com/4309735/150698674-a8d80704-5bab-4c3e-a5f7-4357ad79f611.mov
> Fix bugs (android keyboard, user label, search bar width)

- src/client/navigation/screens/create_account/CreateAccountScreen.tsx
https://user-images.githubusercontent.com/3479724/150722048-b33c1bc8-4418-4c11-9fbf-6b57f2ca2199.mov
> show password hints

- src/client/create_request/__generated__/CreateAidRequestMutation.ts
- src/client/request_explorer/AidRequestCard.tsx
- src/client/request_explorer/AidRequestCardFragments.ts
- src/client/request_explorer/__generated__/AidRequestCardFragment.ts
- src/client/request_explorer/__generated__/ListOfAidRequestsQuery.ts
- src/client/request_explorer/__generated__/editAidRequestMutation.ts
and when i delete one of the crews from my user:
> show crew in ui (iff viewer in multi crews)

- src/server/collections/aid_request/helpers/loadAidRequestForViewer.ts
> fix caching bug

- src/client/components/Colors.ts
- src/client/components/TextInput.tsx
- src/client/navigation/screens/create_account/CreateAccountScreen.tsx
- src/client/navigation/screens/login/LoginScreen.tsx
1. Require password confirmation on register
2. Keyboard buttons to advance to next page
3. Give user a link to email Lowell if login fails
https://user-images.githubusercontent.com/4309735/151465548-c3c562eb-0b10-4e07-b960-0a2f6921789f.mov
> Improve Register / Login UX

- src/server/root/runserver.ts
https://user-images.githubusercontent.com/4309735/152021508-db86588f-d959-49fa-bbf7-aaefee5746f1.mov
> Implement hot reloading with auto-refresh

- package.json
- src/client/aid_request/create/__generated__/CreateAidRequestsMutation.ts
- src/client/aid_request/detail/AidRequestDetailScreen.tsx
- src/client/aid_request/drafts/AidRequestDraftIDs.ts
- src/client/components/Button.tsx
- src/client/components/ErrorScreen.tsx
- src/client/utils/__generated__/CreateErrorReportMutation.ts
- src/client/utils/useDebugInfo.ts
- src/server/collections/aid_request/helpers/loadAidRequestForViewer.ts
- src/server/graphql/GraphQLSchema.ts
- src/server/graphql/reportError.ts
- yarn.lock
Thought it'd be nice to have an experience other than "blank screen" when accessing an invalid link (e.g., a link someone sent you to something you don't have permission to view)
https://user-images.githubusercontent.com/4309735/152236510-4e3bec71-491c-457a-a857-a50df779276f.mov
> Aid request not found

- src/client/aid_request/create/CreateRequestScreen.tsx
- src/client/aid_request/create/CreateRequestTabStackContainer.tsx
- src/client/aid_request/create/RecordAidRequestForm.tsx
- src/client/aid_request/detail/AidRequestDetailScreen.tsx
- src/client/aid_request/explorer/RequestExplorerHeader.tsx
- src/client/aid_request/explorer/RequestExplorerScreen.tsx
- src/client/aid_request/explorer/RequestExplorerTabStackContainer.tsx
- src/client/aid_request/filter/RequestExplorerFilters.tsx
- src/client/components/Colors.ts
- src/client/components/Header.tsx
- src/client/components/ScrollableScreen.tsx
- src/client/components/StaticScrollableList.tsx
- src/client/components/theme/ReactNativePaperTheme.ts
- src/client/components/useViewWidth.ts
- src/client/menu/ThreeLinesMenuScreen.tsx
- src/client/menu/ThreeLinesMenuTabStackContainer.tsx
- src/client/navigation/Navigation.tsx
- src/client/navigation/screens/create_account/CreateAccountScreen.tsx
- src/client/navigation/screens/login/LoginScreen.tsx
- src/client/navigation/screens/not_logged_in/NotLoggedInScreen.tsx
- src/client/navigation/screens/record_aid_request/RecordAidRequestScreen.tsx
- src/server/collections/aid_request/AidRequestModel.ts
- src/server/collections/aid_request/AidRequestModelTypes.ts
- src/server/collections/aid_request/computed_fields/getComputedFields.ts
- src/server/collections/aid_request/mutations/createAidRequests.ts
- src/server/collections/aid_request/mutations/editAidRequest.ts
- src/server/collections/aid_request/query_fields/allAidRequests/allAidRequests.ts
- src/server/scripts/set-precomputed-fields.ts
1. sort by last updated
2. create a maximum width so that the UI looks more reasonable on desktop
3. update header and footer colors to material design 3
> sort by last updated (+more)

- __generated__/globalTypes.ts
- package.json
- src/client/aid_request/detail/AidRequestDetailScreen.tsx
- src/client/aid_request/detail/__generated__/AidRequestDetailsQuery.ts
- src/client/aid_request/detail/add-a-comment/AddAComment.tsx
- src/client/aid_request/detail/rows/WhatIsNeeded.tsx
- src/client/aid_request/detail/rows/WhoIsItFor.tsx
- src/client/aid_request/edit/useEditAidRequestWithUndo.ts
- src/client/aid_request/list/__generated__/ListOfAidRequestsQuery.ts
- src/client/components/InlineEditableText.tsx
- src/client/error/initErrorLogging.ts
- src/client/graphql/useMutateWithUndo.ts
- src/server/collections/aid_request/AidRequestGraphQLTypes.ts
- src/server/collections/aid_request/AidRequestModel.ts
- src/server/collections/aid_request/AidRequestModelTypes.ts
- src/server/collections/aid_request/helpers/getHistoryEventSummary.ts
- src/server/collections/aid_request/helpers/getHistoryWithoutRemovals.ts
- src/server/collections/aid_request/mutations/edit/UpdateType.ts
- src/server/collections/aid_request/mutations/edit/executors/changeStringField.ts
- src/server/collections/aid_request/mutations/edit/executors/changeWhatIsNeeded.ts
- src/server/collections/aid_request/mutations/edit/executors/changeWhoIsItFor.ts
- src/server/collections/aid_request/mutations/editAidRequest.ts
- src/server/collections/aid_request/object_fields/activity.ts
- src/server/collections/aid_request/object_fields/latestEvent.ts
- yarn.lock
With 5 sec of network latency added: https://drive.google.com/file/d/185RhPVGl_-6RT9NdPgpR-lo1Pl-A3RJu/view?usp=sharing
With no latency added: https://drive.google.com/file/d/1y-XPZFKrNhr0Gojzm6KV3qEISl4fN8Pj/view?usp=sharing
> Edit recipient and request title inline

- src/client/aid_request/detail/add-a-comment/draft/DraftComment.ts
- src/server/collections/aid_request/object_fields/latestEvent.ts
- src/shared/utils/mention_utils.ts
> show mark-as-incomplete in latest event

- .github/workflows/deploy-to-aws.yaml
- __generated__/globalTypes.ts
- src/client/components/ErrorNotice.tsx
- src/client/components/SuccessNotice.tsx
- src/client/components/TextInput.tsx
- src/client/navigation/LinkingConfiguration.ts
- src/client/navigation/NavigationTypes.ts
- src/client/navigation/helpers/useCreateCrumbtrailsToLandingScreenIfNeeded.ts
- src/client/navigation/root/RootNavigation.tsx
- src/client/navigation/screens/create_account/CreateAccountScreen.tsx
- src/client/navigation/screens/login/LoginScreen.tsx
- src/client/navigation/screens/login/__generated__/SendPasswordResetEmail.ts
- src/client/navigation/screens/not_logged_in/NotLoggedInScreen.tsx
- src/client/navigation/screens/reset_password/PasswordResetLinkDetails.tsx
- src/client/navigation/screens/reset_password/ResetPasswordScreen.tsx
- src/client/navigation/screens/reset_password/__generated__/ResetPasswordLinkDetailsQuery.ts
- src/client/navigation/screens/reset_password/__generated__/ResetPasswordMutation.ts
- src/client/utils/useDebugInfo.ts
- src/server/collections/user/UserGraphQLImpl.ts
- src/server/collections/user/UserModelTypes.ts
- src/server/collections/user/mutations/resetPassword.ts
- src/server/collections/user/mutations/sendPasswordResetEmail.ts
- src/server/collections/user/root_fields/resetPasswordLinkDetails.ts
- src/server/email/EmailTemplateTypes.ts
- src/server/email/sendEmail.ts
- src/server/utils/crypto/__tests__/encryption.test.ts
- src/server/utils/crypto/encryption.ts
- src/shared/urls/PASSWORD_RESET_PATH.ts
- src/shared/urls/TOKEN_URL_PARAM.ts
- src/shared/urls/passwordResetUrl.ts
Support resetting your password
> password reset

- .devcontainer/devcontainer.json
- package.json
- src/client/host/host.ts
- src/server/collections/aid_request/helpers/aidRequestHasBeenDeleted.ts
- src/server/collections/aid_request/helpers/loadAidRequestForViewer.ts
- src/server/collections/aid_request_reminder/executeReminder.ts
- src/server/collections/aid_request_reminder/executeReminders.ts
- src/server/email/sendEmail.ts
- src/server/root/web_request_listener/index.ts
- src/shared/urls/getDomain.ts
- src/shared/urls/getDomainAndProtocol.ts
- src/shared/urls/getEmailAddress.ts
- src/shared/urls/getProtocol.ts
previously, when you tried to reset your password in the dev environment, it would send a link to the production environment
> Support password reset on localhost

- .eslintrc.js
- package.json
- src/server/collections/aid_request/mutations/edit/executors/changeStringField.ts
- src/server/collections/aid_request/mutations/edit/executors/comment.ts
- src/server/collections/aid_request/mutations/edit/executors/workingOn.ts
- src/server/collections/aid_request_reminder/executeReminders.ts
- src/server/collections/user/UserModel.ts
- src/server/collections/user/mutations/sendPasswordResetEmail.ts
- src/server/error/logServerError.ts
- src/server/mongo/client.ts
- src/server/notifications/notify.ts
- src/server/utils/afterRequestIsComplete.ts
- src/server/utils/setTimeoutSafe.ts
- src/server/utils/sleep.ts
- yarn.lock
add a function wrapping setTimeout that catches and logs any errors. this prevents the server from crashing. also created a lint rule to remind me to use this function instead of setTimeout.
> implement setTimeoutSafe

- src/client/aid_request/detail/AidRequestDetailScreen.tsx
- src/client/aid_request/detail/components/Row.tsx
- src/client/aid_request/detail/rows/CrewInfo.tsx
- src/shared/strings/CrewStrings.ts
> show crew name on aid request detail screen

- src/client/viewer/useHandleViewer.ts
- src/server/analytics/index.ts
- src/server/collections/aid_request/query_fields/allAidRequests/helpers/getSearchFilter.ts
- src/server/collections/user/UserModel.ts
- src/server/email/sendEmail.ts
- src/server/email/validateEmailTemplateIDs.ts
- src/server/error/throwError.ts
- src/server/mongo/client.ts
- src/server/root/web_request_listener/index.ts
- src/server/utils/crypto/encryption.ts
- src/shared/env/ENVIRONMENT_IS_USING_TEST_DATABASE.ts
- src/shared/env/env.ts
- src/shared/env/environmentIsUsingHotReloading.ts
- src/shared/env/environmentIsUsingTestDatabase.ts
- src/shared/env/getEnvironmentVariableAndReturnUndefinedIfNotFound.ts
- src/shared/env/getEnvironmentVariableAndThrowIfNotFound.ts
- src/shared/urls/getDomain.ts
- src/shared/urls/getProtocol.ts
every time we access an environment variable, be explicit about whether we should return undefined or throw an exception if it is not found
> explicit environment variable access
